In [140]:
import numpy as np 
neuron = 4 

In [141]:
def sigmoid(x): 
    return 1.0/(1+ np.exp(-x)) 

In [142]:
def sigmoid_derivative(x): 
    return x * (1.0 - x)

In [143]:
class NeuralNetwork: 
    def __init__(self, x, y): 
        self.input = x 
        print('inputs \n' , self.input) 
        print('==================================') 
        self.weights1 = np.random.rand(self.input.shape[1],neuron) 
        print('weights1 \n',self.weights1) 
        print('==================================') 
        self.weights2 = np.random.rand(neuron,1) 
        print('weights2 \n',self.weights2) 
        print('==================================') 
        self.y = y 
        print('y \n',self.y) 
        print('==================================') 
        self.output = np.zeros(self.y.shape) # y hat 
        print('output \n',self.output) 
        print('==================================') 
        
    def feedforward(self): 
        self.layer1 = sigmoid(np.dot(self.input, self.weights1)) 
#=======print('layer 1 \n',self.layer1) 
#=======print() 
        self.output = sigmoid(np.dot(self.layer1, self.weights2)) 
#=======print('output \n',self.output) 
#=======print() 


    def backprop(self): 
#=======application of the chain rule to find derivative of the loss function with respect to weights2 and weights1 
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output))) 
#=======print('d_weights2 \n',d_weights2 ) 
#=======print() 
        
        d_weights1 = np.dot(self.input.T, (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output),
                                                  self.weights2.T) * sigmoid_derivative(self.layer1))) 
#=======print('d_weights1 \n',d_weights1) 
#=======print() 

#=======update the weights with the derivative (slope) of the loss function 
        self.weights1 += d_weights1 
        self.weights2 += d_weights2 

In [144]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1], 
              [1,1,1]]) 
print(X)
y = np.array([[1], 
              [0], 
              [1], 
              [0]]) 
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[1]
 [0]
 [1]
 [0]]


In [145]:
nn = NeuralNetwork(X,y) 

for i in range(10000):
    nn.feedforward() 
    nn.backprop() 

print(nn.output)

a= np.around(nn.output,decimals=1)
print('==================================')
print('rounded int output =')
print(a.astype(int))

inputs 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
weights1 
 [[0.94974502 0.50856357 0.99715447 0.58289448]
 [0.38028919 0.67927592 0.09886615 0.32573009]
 [0.5688247  0.36198767 0.97916373 0.43777667]]
weights2 
 [[0.74027634]
 [0.16629801]
 [0.32352414]
 [0.14836908]]
y 
 [[1]
 [0]
 [1]
 [0]]
output 
 [[0.]
 [0.]
 [0.]
 [0.]]
[[0.99649772]
 [0.00292462]
 [0.99702992]
 [0.00335849]]
rounded int output =
[[1]
 [0]
 [1]
 [0]]
